### ISSUE TITLE
Collect raw counters

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/disco#14]
Currently the archive output reports deltas rather than the original counters. This is largely to preserve backward compatibility with the archive output from the discov1 service.

Discov2 should also export the original SNMP counter values. This provides at least two benefits:

* all deltas can be recalculated using the counter values.
* errors in delta calculations can be corrected
* average rates are trivial to calculate over arbitrary time intervals.

The SNMP counters are the "ground truth" for the disco data.

**Comment by nkinkade** [comment]
This was completed by PR #15.
