### ISSUE TITLE
Impossibly high switch throughput rates at MTY01

### ISSUE THREAD

**Issue by nkinkade** [m-lab/disco#18]
A week or so ago I noticed some anomalous switch throughput values that were impossibly high at MTY01:

![Screenshot from 2021-02-17 16-13-01](https://user-images.githubusercontent.com/1392825/108280212-15578b00-713b-11eb-8422-53f0deba16ce.png)

Clearly a rate of 250 petabytes/sec is an impossibility. What caused this? Likely possibilities include:

* Flaky SNMP on the MTY01 switch
* A bug in DISCOv2

**Comment by nkinkade** [comment]
This query was useful in finding impossible large deltas between samples:

```
SELECT
  sample.timestamp,
  sample.value,
  task_filename
FROM
  `mlab-oti.utilization.switch`,
  UNNEST(sample) AS sample
WHERE
  partition_date = "2021-02-10"
  AND metric = "switch.octets.uplink.tx"
  AND hostname = "mlab1-mty01.mlab-oti.measurement-lab.org"
  AND sample.timestamp BETWEEN TIMESTAMP("2021-02-10 18:00:00")
  AND TIMESTAMP("2021-02-10 18:30:00")
ORDER BY
  sample.timestamp
```

... it also pointed me to the archive file to look into for raw counter values, which led me to discover things like this in the raw data:

```
    {
      "timestamp": 1612981070,
      "collectstart": 1612981070000768500,
      "collectend": 1612981070060876000,
      "value": 18446743695467606000,
      "counter": 30820689
    },
    {
      "timestamp": 1612981080,
      "collectstart": 1612981080000761900,
      "collectend": 1612981080038685200,
      "value": 417,
      "counter": 30821106
    },
    {
      "timestamp": 1612981090,
      "collectstart": 1612981090000789500,
      "collectend": 1612981090039471900,
      "value": 378248245507,
      "counter": 378279066613
    },
    {
      "timestamp": 1612981100,
      "collectstart": 1612981100000738600,
      "collectend": 1612981100052230400,
      "value": 18446743695461306000,
      "counter": 30821987
    },
    {
      "timestamp": 1612981110,
      "collectstart": 1612981110000778200,
      "collectend": 1612981110042228000,
      "value": 417,
      "counter": 30822404
    },
```

The `counter` field records the raw value taken from the switch during that poll. The value should _never_ go backward, yet it does. And not only does it go backward, but I can see that when it does the `value` field is incorrect. Values are stored as `uint64`s, so when an operation results in a negative number the resulting value will not be expected.

**Comment by nkinkade** [comment]
Over the past 7 days, this issue seems to be affecting a few sites: MTY01, MIA02 and MNL02:

![Screenshot from 2021-02-17 16-35-45](https://user-images.githubusercontent.com/1392825/108282128-49807b00-713e-11eb-88c1-cebad984ad53.png)

**Comment by nkinkade** [comment]
Add LGA04:

![Screenshot from 2021-02-17 16-45-00](https://user-images.githubusercontent.com/1392825/108282857-8ac55a80-713f-11eb-8488-bd6dc52f8107.png)

**Comment by robertodauria** [comment]
This Reddit post (!) from 9 months ago seems relevant: https://www.reddit.com/r/Juniper/comments/gg6fg6/juniper_qfx5100_snmp_polling_issue_highincorrect/

It seems JunOS 18.4R2-S3 might have fixed this?

**Comment by nkinkade** [comment]
To rule out that this could be fundamentally a DISCOv2 or gosnmp bug, I ran the following script from mlab4-mty01 for around 45 minutes:

```
# Get ifDescr values into the file so related human-readable interface names with logical interface numbers.
snmpwalk -c <community> -v2c s1-mty01.measurement-lab.org 1.3.6.1.2.1.2.2.1.2 > ifstats

while true; do
    snmpwalk -c <community> -v2c s1-mty01.measurement-lab.org .1.3.6.1.2.1.31.1.1.1.10 | tee -a ifstats
    echo -e "\n\n" >> ifstats
    sleep 10
done
```

Interface 515 is `xe-0/0/0` (mlab1). And a sample of the content of the file looks like this:

```
mlab@mlab4-mty01:~$ grep "iso.3.6.1.2.1.31.1.1.1.10.515" ifstats | head -n 20
iso.3.6.1.2.1.31.1.1.1.10.515 = Counter64: 717559951815
iso.3.6.1.2.1.31.1.1.1.10.515 = Counter64: 717574160848
iso.3.6.1.2.1.31.1.1.1.10.515 = Counter64: 717599196431
iso.3.6.1.2.1.31.1.1.1.10.515 = Counter64: 717609747587
iso.3.6.1.2.1.31.1.1.1.10.515 = Counter64: 60667470
iso.3.6.1.2.1.31.1.1.1.10.515 = Counter64: 60667934
iso.3.6.1.2.1.31.1.1.1.10.515 = Counter64: 717640903871
iso.3.6.1.2.1.31.1.1.1.10.515 = Counter64: 717648239398
iso.3.6.1.2.1.31.1.1.1.10.515 = Counter64: 717650757040
iso.3.6.1.2.1.31.1.1.1.10.515 = Counter64: 60669658
iso.3.6.1.2.1.31.1.1.1.10.515 = Counter64: 717656793150
iso.3.6.1.2.1.31.1.1.1.10.515 = Counter64: 717670167824
iso.3.6.1.2.1.31.1.1.1.10.515 = Counter64: 717678311684
iso.3.6.1.2.1.31.1.1.1.10.515 = Counter64: 60671382
iso.3.6.1.2.1.31.1.1.1.10.515 = Counter64: 60671800
iso.3.6.1.2.1.31.1.1.1.10.515 = Counter64: 60672264
iso.3.6.1.2.1.31.1.1.1.10.515 = Counter64: 717712796270
iso.3.6.1.2.1.31.1.1.1.10.515 = Counter64: 60673568
iso.3.6.1.2.1.31.1.1.1.10.515 = Counter64: 60673986
iso.3.6.1.2.1.31.1.1.1.10.515 = Counter64: 717740142022
```

This would seem to indicate that the issue has nothing to do with DISCOv2 or gosnmp, but is located in the switch.

**Comment by nkinkade** [comment]
I have search for bugs filed against JunOS related to SNMP that might explain our problem. I found only a single issue that looked like it could be related (that wasn't already fixed in our release):

https://prsearch.juniper.net/InfoCenter/index?page=prcontent&id=PR1508442 (login required)
```
Number | PR1508442
Title | SNMP polling might return unexpectedly high value of ifHCOutOctets counter for physical interface when any jnxDom OID is processed at the same time.
Release Note | When actual transmitted load is configured for interface as:  set interfaces <interface name> interface-transmit-statistics  And ifHCOutOctets OID is polling together with any jnxDom OIDs for the same interface with time interval between pollings equal or less then one second, the resulted value of ifHCOutOctets may be  unexpectedly high | When actual transmitted load is configured for interface as:  set interfaces <interface name> interface-transmit-statistics  And ifHCOutOctets OID is polling together with any jnxDom OIDs for the same interface with time interval between pollings equal or less then one second, the resulted value of ifHCOutOctets may be  unexpectedly high
```

The issue claims this bug is fixed in 18.4R2-S6, but the most recent "recommended" version in the 18.x line for QFX5100s is 18.4R2-S5.

Even still, this issue does not seem to closely describe what we are seeing. We are not seeing unexpectedly high values, but instead see counters going backward by a large margin.

I'm going to open a case with Juniper to see what they say.

**Comment by nkinkade** [comment]
Ugh. I cannot open a support case with Juniper because every switch we have seems to either not have a software support contract (hardware only), or the support contract has already ended (several ended on Dec 31, 2020). <sigh>

I guess this means we are stuck with a fleet of switch with an apparent bug, for which we have no recourse to the manufacturer.

I guess I'll try updating JunOS on s1-mty01 (a switch which actively presents this problem every few minutes) to the latest 18.x version recommended by the JTAC (18.4R2-S5).

**Comment by nkinkade** [comment]
I upgraded Jun0S on s1-mty01, and it seems to have, at least temporarily, fixed the issue with SNMP counters flapping around: 

https://grafana.mlab-oti.measurementlab.net/explore?orgId=1&left=%5B%221613672380646%22,%221613719286466%22,%22Platform%20Cluster%20(mlab-oti)%22,%7B%22expr%22:%22ifHCOutOctets%7Bmachine%3D~%5C%22mlab1-mty01.*%5C%22%7D%5Cn%22,%22requestId%22:%22Q-5709d140-8e7c-42e0-846a-177938bc05ca-0A%22%7D%5D

What I need to do today is a control of some sort. It's not clear yet whether the firmware upgrade fixed the issue, or whether it could have been simply rebooting the switch. I'll find another site that is equally bad off at MTY01 was, and then try to restart l2-learning, and maybe restart the snmp process, if nothing improves I'll reboot with no other changes. If that doesn't fix the issue, then I'll upgrade JunOS. If that fixes the issue, then we can start to look into upgrading JunOS on all switches. However, I'd like for the fix to this to make it into our next JunOS upgrade: https://github.com/m-lab/ops-tracker/issues/1187

**Comment by nkinkade** [comment]
On MNL02, another switch with fairly severe symptoms of this issue, I tried restarting both the "l2-learning" and "snmp" services, with no visible change in behavior. I tried rebooting the switch, with no visible change in behavior. This starts to make it seem like:

* the upgraded JunOS version on MTY01 fixes the issue
* something about upgrading JunOS (temporarily?) causes the problem to go away.

I'd like to assume the former.  We should probably look into upgrading all switches.

Also, it sort of looks like rebooting the MNL02 switch actually made the problem worse:

https://grafana.mlab-oti.measurementlab.net/explore?orgId=1&left=%5B%221613760788130%22,%221613771633481%22,%22Platform%20Cluster%20(mlab-oti)%22,%7B%22expr%22:%22ifHCOutOctets%7Bmachine%3D~%5C%22mlab1-mnl02.*%5C%22%7D%22,%22requestId%22:%22Q-aa27ded9-8da7-4817-96f3-122a4310d954-0A%22%7D%5D

**Comment by nkinkade** [comment]
Experimenting on s1-mty01 and s1-mnl02, we have found that upgrading JunOS to 18.4R2.7 seems to resolves this issue. The plan is to upgrade all switches to fix and apparent bug in the version of JunOS we are running. Closing this because upgrading the switches is a separate issue.
